export { default as SWelcome } from './SWelcome'
export { default as SConfirmPhoneNum } from './SConfirmPhoneNum'
export { default as OTP } from './OTP'
export { default as SForgotPassword } from './SForgotPassword'
export { default as MainScreen } from './MainScreen'